// Generated by CoffeeScript 2.7.0
var all_os, color_map, csv, events, get_os_color, i, init, int, j, len, os_colors, quarter_charts, quarter_data, quarter_pie, quarters_index, selected_idx, selected_os_idx, selected_quarter, timeline_data, timeline_os;

all_os = ['Bada', 'Android', 'iOS', 'RIM', 'Symbian', 'Windows Mobile', 'Windows Phone', 'Other'];

timeline_os = ['Android', 'iOS', 'RIM', 'Symbian', 'Windows Phone'];

csv = null;

quarter_data = [];

quarters_index = {};

selected_idx = null;

selected_os_idx = 0;

selected_quarter = [];

timeline_data = [];

// make sure colors are consistent across graphs
color_map = {};

os_colors = d3.zip(all_os, d3.scale.category10().range());

for (j = 0, len = os_colors.length; j < len; j++) {
  i = os_colors[j];
  color_map[i[0]] = i[1];
}

get_os_color = function(os) {
  if (color_map.hasOwnProperty(os)) {
    return color_map[os];
  }
  return '#eeeeee';
};

int = function(v) {
  return parseInt(v, 10);
};

quarter_pie = function() {
  var os_percentage, other_os, other_percentage, selected_os, so, total_smartphones;
  // calculate other smartphone value from OS with hightest share and total smartphone value
  selected_os = quarter_data[selected_os_idx];
  total_smartphones = int(selected_quarter['Total Smartphones']);
  other_os = total_smartphones - selected_os.value;
  os_percentage = selected_os.value ? 100 / total_smartphones * selected_os.value : 0;
  other_percentage = other_os ? 100 / total_smartphones * other_os : 0;
  pie('#quarter-share', [
    {
      'label': selected_os.label,
      'value': os_percentage
    },
    {
      'label': 'All else',
      'value': other_percentage
    }
  ]);
  so = d3.select('#select-os');
  so.selectAll('option').remove();
  so.selectAll('option').data(quarter_data).enter().append('option').attr('value', function(d, i) {
    return i;
  }).attr('selected', function(d, i) {
    if (int(selected_os_idx) === i) {
      return 'selected';
    } else {
      return null;
    }
  }).text(function(d) {
    return d.label;
  });
  return so.on('change', function() {
    selected_os_idx = d3.event.target.value;
    return quarter_pie();
  });
};

quarter_charts = function() {
  var k, len1, os, val;
  selected_quarter = csv[selected_idx];
  quarter_data = [];
  for (k = 0, len1 = all_os.length; k < len1; k++) {
    os = all_os[k];
    val = int(selected_quarter[os]);
    if (val) {
      quarter_data.push({
        'label': os,
        'value': val
      });
    }
  }
  quarter_data.sort(function(a, b) {
    return d3.descending(a.value, b.value);
  });
  bar('#quarter-all-os', [
    {
      'key': selected_quarter['Quarter'],
      'values': quarter_data
    }
  ]);
  // must reset selected_os_idx before creating pie
  selected_os_idx = 0;
  return quarter_pie();
};

// set up event handlers
events = function() {
  var sq;
  d3.select('#select-chart-type').on('change', function() {
    // remove to avoid overlaying charts
    d3.select('#timeline').selectAll('*').remove();
    return timeline('#timeline', timeline_data, d3.event.target.value, get_os_color);
  });
  sq = d3.select('#select-quarter');
  sq.selectAll('option').data(d3.entries(quarters_index)).enter().append('option').attr('value', function(d) {
    return d.value;
  }).attr('selected', function(d) {
    if (selected_idx === int(d.value)) {
      return 'selected';
    } else {
      return null;
    }
  }).text(function(d) {
    return d.key;
  });
  return sq.on('change', function() {
    selected_idx = d3.event.target.value;
    return quarter_charts();
  });
};

init = function(error, data) {
  var d, date, idx, k, l, len1, len2, os, os_sum, other, row, val, values, values_by_os;
  csv = data;
  values_by_os = {};
// over time chart
  for (k = 0, len1 = timeline_os.length; k < len1; k++) {
    os = timeline_os[k];
    values_by_os[os] = [];
  }
  values_by_os['Other'] = [];
  for (idx in csv) {
    row = csv[idx];
    os_sum = 0;
    quarters_index[row['Quarter']] = idx;
    d = row.Date.split('-');
    date = new Date(int(d[0]), int(d[1]) - 1, int(d[2])).getTime();
    for (l = 0, len2 = timeline_os.length; l < len2; l++) {
      os = timeline_os[l];
      val = int(row[os]);
      os_sum += val;
      values_by_os[os].push([date, val]);
    }
    //values_by_os[os].push {'x': date, 'y': val} # for multiBarChart
    other = int(row['Total Smartphones']) - os_sum;
    values_by_os['Other'].push([date, other]);
  }
  for (os in values_by_os) {
    values = values_by_os[os];
    timeline_data.push({
      'key': os,
      'values': values
    });
  }
  timeline('#timeline', timeline_data, 'area', get_os_color);
  // by default show latest quarter with data
  selected_idx = csv.length - 1;
  quarter_charts();
  return events();
};

queue().defer(d3.csv, '/data/mobile-os-market-share.csv').await(init);
